### ISSUE TITLE
Stringify params/signature

### ISSUE THREAD

**Issue by baohouse** [tim-kos/transloadit_xhr#9]
I don't know if other people are facing the same problem but I had to apply JSON.stringify() to the params and signature to get it working. You may want to do a simple type check on params and signature objects; if it's a string, then it's *probably* a stringified JSON; if it's an object, then you'll want to stringify it.

**Comment by alexthewilde** [comment]
+1

**Comment by tim-kos** [comment]
Implemented in c8d1516dc75d8ac382718a2bf6fe157063b9a97e

Best,
Tim
